### ISSUE TITLE
Search through thunderbird mails

### ISSUE THREAD

**Issue by tobiasstrauss** [WolfgangFahl/pyThunderbird#15]
**What I want to do:**
I need a python access to my Thunderbird mails. I want to search for specific contents and mail addresses. The description in the readme suggests that this is the purpose of this package.

**What I already did** 
I tried to access `Thunderbird`-class. Unfortunately, this class needs a `.thunderbird.yaml` in the home directory. 
I have no idea about the content of this file. Could you provide a template?
Also I do not know which `db` to pass.
Then, how do I search through the mails?

**Comment by WolfgangFahl** [comment]
@tobiasstrauss thank your for trying to use this library. I added a configuration section to the wiki to answer your question about the yaml file. For the search part you are probably looking into a frontend solution. Could you please create a mockup of how you'd like to expect the search to look like e.g. just a single search field + a button and maybe a selection of the user (s)? 

https://github.com/WolfgangFahl/pyThunderbird/milestone/6 has the issues that are due for the next milestone. It will be a few weeks until i get to work in detail on this but for beginning of 2024 we might get this working (pull requests welcome).

**Comment by WolfgangFahl** [comment]
@tobiasstrauss could you please look into the current state of affairs and test whether the create index command line option works for you?

```bash
tbmail -h
...
-ci, --create-index   create an alternative index for the given users's
                        Thunderbird mailarchive
```

This will create a second sqlite database that has the cached table of contents information see https://github.com/python/cpython/issues/112429

Searching messages content should be easier with this approach. In my own environm ent i just indexed some 1000 mailboxes with 350k + mails successfully. Just let us know what search options you'd like to get and we can go from there.

**Comment by WolfgangFahl** [comment]
Personally i use local folders to be able to backup everything end i purposely don't use the IMAP folder. 

So please try a local folder and let me know how important the IMAP feature is for you. 
In the meantime the nicegui migration is making good progress. The display of messages and attachments needs to be improved otherwise it's now possible to walk thru folders and get to individual messages. The search feature should now be easy to implement depending on what you want - global keyword search - or search by subject/receiver/sender - by date? A combination of these? Or just programmatic access to the database? The index_db i am now creating is much smaller than the gloda but very fast.

**Comment by WolfgangFahl** [comment]
Here is a screenshot:
![grafik](https://github.com/WolfgangFahl/pyThunderbird/assets/1336221/47da535f-bced-4511-9071-eb4c7d9d0763)

**Comment by WolfgangFahl** [comment]
![grafik](https://github.com/WolfgangFahl/pyThunderbird/assets/1336221/1ad4e28c-d61c-4ab6-943a-ea30d8697a01)

**Comment by tobiasstrauss** [comment]
thanks for your effort. I'll test it the next days.

**Comment by WolfgangFahl** [comment]
Just contact me thru the contact link on my companies website or by e-mail if you'd like to do an online zoom session to find out how to make the library work for you.
